### ISSUE TITLE
Infografía de librería

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/infografia-de-las-librerias-FedericoVictorianoSierra#2]
El estudiante debe realizar  una infografía con los conceptos y funciones de una librerías o componentes y su aplicación en las Apps.

- La infografía debe tener un buen diseño y contener la información correcta

**Comment by FedericoVictorianoSierra** [comment]
[Infografia Librerias (Federico Victoriano Sierra($US)).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-FedericoVictorianoSierra/files/8210655/Infografia.Librerias.Federico.Victoriano.Sierra.US.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Infografia Librerias (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-FedericoVictorianoSierra/files/8210661/Infografia.Librerias.Federico.Victoriano.Sierra.4US.pdf)

**Comment by FedericoVictorianoSierra** [comment]
[Infografia Librerias (Federico Victoriano Sierra(4US)).pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-las-librerias-FedericoVictorianoSierra/files/8211163/Infografia.Librerias.Federico.Victoriano.Sierra.4US.pdf)

**Comment by OFELHER93** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
